services:
  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 8001:8001
  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_USER: bustracker
      POSTGRES_PASSWORD: QsPkHJ0696UDf6UX
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
